### PR TITLE
Moved the contentCache next to the user settings folder.

### PR DESCRIPTION
**Pull request by JunielKatarn**
Instead of being all by itself under %LOCALAPPDATA%, it can join its user settings folder friends at %LOCALAPPDATA%\Jammit.

### CODE REVIEW

**Comment by maxton** [comment]
Can you change this to match what is said in #23 ?

**Comment by JunielKatarn** [comment]
Can you please clarify what exactly should match #23?

* The .xml extension?
* The `%LOCALAPPDATA%\Jam.NET` root folder? (Note: user settings would still be placed under a 'random' fulder in `%LOCALAPPDATA%\Jammit`, due to the root namespace setting).

**Comment by maxton** [comment]
Both, so the file should be in `%LOCALAPPDATA%\Jam.NET\contentCache.xml`. Then, later, the user settings will be refactored to go in the same directory (no longer using the .NET `Properties.Settings.Default` etc)

**Comment by JunielKatarn** [comment]
Updated `contentCache` location.

**Pull request merged**
